import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;

/**
 * Native ASP.NET local-registration bridge.
 *
 * Instead of manufacturing a regName in the GUI process, this adapter opens the
 * application's own Regester/Register.aspx local-registration page, consumes the
 * sequence number generated by the application, creates the matching offline code,
 * submits the original ASP.NET form and then verifies the regName written by the
 * application itself. This keeps HttpContext/AppDomain-dependent vendor logic inside
 * IIS, where the application normally runs.
 */
public final class LicenseRecoverModernGUIDotNetIisRegistration {
    private static final Pattern INPUT = Pattern.compile("(?is)<input\\b[^>]*>");
    private static final Pattern ATTR = Pattern.compile("(?is)([A-Za-z_:][A-Za-z0-9_:.\\-]*)\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s>]+))");
    private static final Pattern AUTH_URL = Pattern.compile("(?i)https?://regservice\\.itmc\\.cn(?::\\d+)?(?:/[^\\s<>\\\"']*)?");
    private static final String BLOCK = LicenseRecoverModernGUIAutoRecovery.BLOCK_ENDPOINT;

    private LicenseRecoverModernGUIDotNetIisRegistration() { }

    static final class FormPage {
        final URL url;
        final LinkedHashMap<String,String> fields = new LinkedHashMap<String,String>();
        String seqName, codeName, submitName, submitValue, sequence, cookie;
        FormPage(URL u) { url = u; }
    }

    static LicenseRecoverModernGUIAutoRecovery.Result recover(
            LicenseRecoverModernGUIAutoRecovery.Detection d,
            boolean backup, boolean blockNet, boolean dryRun, Consumer<String> logger) throws Exception {
        Consumer<String> log = logger == null ? x -> { } : logger;
        if (d == null || d.appRoot == null || d.runtimeDir == null)
            return new LicenseRecoverModernGUIAutoRecovery.Result(false, "IIS application path is unavailable.", d, null, null, null);
        if (blank(d.productName))
            return new LicenseRecoverModernGUIAutoRecovery.Result(false, "Could not determine the target ProName safely; no file was changed.", d, null, null, null);

        File pageFile = findRegistrationPage(d.appRoot);
        if (pageFile == null)
            return new LicenseRecoverModernGUIAutoRecovery.Result(false,
                    "未找到应用自己的 Regester.aspx/Register.aspx，本次不会回退到直接伪造 regName。", d, null, null, null);

        List<URL> candidates = resolveLocalUrls(d.appRoot, pageFile.getName(), log);
        FormPage form = null;
        Exception last = null;
        for (URL u : candidates) {
            try {
                FormPage candidate = getForm(u);
                if (!blank(candidate.sequence) && !blank(candidate.seqName) && !blank(candidate.codeName)) {
                    form = candidate;
                    break;
                }
            } catch (Exception ex) {
                last = ex;
            }
        }
        if (form == null) {
            String detail = last == null ? "registration page did not expose a native sequence number" : last.getMessage();
            return new LicenseRecoverModernGUIAutoRecovery.Result(false,
                    "无法从本机 IIS 应用取得原生申请号：" + detail + "。请先确认站点/应用池已启动。", d, null, null, null);
        }

        String decoded = LicenseRecoverModernGUIAutoRecovery.desDecryptHex(form.sequence, "itmcsoft");
        if (decoded == null || decoded.length() < 43)
            return new LicenseRecoverModernGUIAutoRecovery.Result(false, "应用生成的申请号无法按原生 itmcsoft 协议解析。", d, null, form.sequence, null);
        String machine = decoded.substring(4, 20);
        String requestTime = decoded.substring(24, 43);
        if (machine.length() != 16)
            return new LicenseRecoverModernGUIAutoRecovery.Result(false, "应用原生申请号中的 RegID 不是 16 位。", d, machine, form.sequence, null);

        String regStr = LicenseRecoverModernGUIAutoRecovery.detectProductList(
                new File(d.runtimeDir, "ITMC.Web.dll"), d.productName);
        if (blank(regStr)) regStr = !blank(d.versionId) ? d.versionId.trim() : d.productName;
        String authPlain = "00" + requestTime + "00" + machine + "00" + "2099-12-31"
                + "00" + "1" + "00" + "-001" + "00" + "-1" + "00" + regStr;
        String auth = LicenseRecoverModernGUIAutoRecovery.desEncryptHex(authPlain, "itmc" + d.productName);

        log.accept("[iis-native] page=" + form.url + "\n");
        log.accept("[iis-native] ProName=" + d.productName + " RegID=" + machine + " products=" + regStr + "\n");
        log.accept("[iis-native] sequence source=application NewRegistry/local registration page\n");

        File cfg = findConfig(d);
        String original = cfg != null && cfg.isFile()
                ? new String(Files.readAllBytes(cfg.toPath()), StandardCharsets.UTF_8) : null;
        String originalRegName = original == null ? null : firstElement(original, "regName");

        if (dryRun) {
            log.accept("[dry-run] would POST the generated local code to the application's own local-registration form.\n");
            return new LicenseRecoverModernGUIAutoRecovery.Result(true,
                    "Preview completed; native IIS form was read but no registration was submitted.", d,
                    machine, form.sequence, auth);
        }

        if (backup && cfg != null && cfg.isFile()) {
            File backupFile = uniqueBackup(cfg);
            Files.copy(cfg.toPath(), backupFile.toPath(), StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES);
            log.accept("[backup] " + backupFile.getAbsolutePath() + "\n");
        }

        try {
            HttpResult submit = submitForm(form, auth);
            log.accept("[iis-native] POST status=" + submit.status + (submit.location == null ? "" : " location=" + submit.location) + "\n");

            if (cfg == null || !cfg.isFile())
                throw new IOException("应用提交后未找到 config.xml，无法确认原生 DoRegistry 写回结果");
            String after = new String(Files.readAllBytes(cfg.toPath()), StandardCharsets.UTF_8);
            String nativeRegName = firstElement(after, "regName");
            if (blank(nativeRegName)) throw new IOException("原生提交后 config.xml 没有 regName");
            if (!blank(originalRegName) && originalRegName.trim().equals(nativeRegName.trim()))
                throw new IOException("原生提交后 regName 未发生变化，应用没有接受本地注册码");

            verifyNativeRegName(nativeRegName.trim(), d.productName, machine, regStr);
            log.accept("[iis-native] native DoRegistry write-back verified with *ITMC" + d.productName + "OK*\n");

            if (blockNet) {
                String blocked = LicenseRecoverModernGUIAutoRecovery.updateLocalLicenseXml(after, nativeRegName.trim(), true);
                Files.write(cfg.toPath(), blocked.getBytes(StandardCharsets.UTF_8));
                blockSidecars(d, backup, log);
                log.accept("[iis-native] residual authorization Service redirected to " + BLOCK + "\n");
            }

            return new LicenseRecoverModernGUIAutoRecovery.Result(true,
                    ".NET IIS 原生本地注册已完成：应用生成申请号 → 自动生成注册码 → 原生表单提交 → 原生 regName 写回验证通过。",
                    d, machine, form.sequence, auth);
        } catch (Throwable ex) {
            if (cfg != null && original != null) {
                try {
                    Files.write(cfg.toPath(), original.getBytes(StandardCharsets.UTF_8));
                    log.accept("[rollback] restored original config.xml after native IIS registration failure.\n");
                } catch (Throwable restore) { ex.addSuppressed(restore); }
            }
            if (ex instanceof Exception) throw (Exception) ex;
            throw new Exception(ex);
        }
    }

    static void verifyNativeRegName(String regName, String product, String machine, String regStr) throws Exception {
        String plain = LicenseRecoverModernGUIAutoRecovery.desDecryptHex(regName, "*ITMC" + product + "OK*");
        if (plain == null || plain.length() < 12) throw new IOException("原生 regName 无法用实际 ProName 解密");
        String json = plain.substring(6, plain.length() - 6);
        if (!json.contains("\"RegID\":\"" + machine + "\""))
            throw new IOException("原生 regName 的 RegID 与应用申请号不一致");
        if (!json.contains("\"ProName\":\"" + product + "\""))
            throw new IOException("原生 regName 的 ProName 与检测结果不一致");
        if (!blank(regStr)) {
            String[] items = regStr.split(",");
            for (String item : items) {
                String x = item.trim();
                if (!x.isEmpty() && !json.contains(x))
                    throw new IOException("原生 regName 缺少授权项 " + x);
            }
        }
    }

    static FormPage parseForm(URL url, String html, String cookie) throws Exception {
        FormPage page = new FormPage(url);
        page.cookie = cookie;
        Matcher m = INPUT.matcher(html == null ? "" : html);
        while (m.find()) {
            String tag = m.group();
            Map<String,String> attrs = attributes(tag);
            String name = attrs.get("name");
            if (blank(name)) continue;
            String type = lower(attrs.get("type"));
            String value = htmlDecode(attrs.get("value"));
            if (value == null) value = "";
            if ("hidden".equals(type)) page.fields.put(name, value);
            String lowerName = name.toLowerCase(Locale.ROOT);
            if (lowerName.endsWith("textbox1") && looksHex(value)) {
                page.seqName = name;
                page.sequence = value.trim();
            }
            if (lowerName.endsWith("textbox2")) page.codeName = name;
            if (("submit".equals(type) || "button".equals(type))
                    && (lowerName.endsWith("button1") || value.contains("本地注册"))) {
                page.submitName = name;
                page.submitValue = value;
            }
        }
        if (blank(page.sequence)) {
            m = INPUT.matcher(html == null ? "" : html);
            while (m.find()) {
                Map<String,String> attrs = attributes(m.group());
                String name = attrs.get("name"), value = htmlDecode(attrs.get("value"));
                if (!blank(name) && looksHex(value) && value.trim().length() > 64) {
                    page.seqName = name; page.sequence = value.trim(); break;
                }
            }
        }
        return page;
    }

    private static FormPage getForm(URL url) throws Exception {
        HttpURLConnection c = open(url);
        c.setRequestMethod("GET");
        int status = c.getResponseCode();
        String cookie = collectCookies(c);
        String html = readResponse(c);
        if (status >= 400) throw new IOException("HTTP " + status + " from " + url);
        return parseForm(url, html, cookie);
    }

    private static HttpResult submitForm(FormPage form, String auth) throws Exception {
        LinkedHashMap<String,String> fields = new LinkedHashMap<String,String>(form.fields);
        fields.put(form.seqName, form.sequence);
        fields.put(form.codeName, auth);
        if (!blank(form.submitName)) fields.put(form.submitName, blank(form.submitValue) ? "本地注册" : form.submitValue);
        byte[] body = encodeForm(fields).getBytes(StandardCharsets.UTF_8);
        HttpURLConnection c = open(form.url);
        c.setInstanceFollowRedirects(false);
        c.setRequestMethod("POST");
        c.setDoOutput(true);
        c.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
        c.setRequestProperty("Content-Length", String.valueOf(body.length));
        if (!blank(form.cookie)) c.setRequestProperty("Cookie", form.cookie);
        OutputStream out = c.getOutputStream();
        try { out.write(body); } finally { out.close(); }
        int status = c.getResponseCode();
        String location = c.getHeaderField("Location");
        String text = readResponse(c);
        if (status >= 400) throw new IOException("native registration POST returned HTTP " + status);
        if (status < 300 && !blank(text)) {
            String lower = text.toLowerCase(Locale.ROOT);
            if (lower.contains("注册失败") || lower.contains("注册码错误") || lower.contains("register.xml"))
                throw new IOException("应用本地注册页明确返回注册失败");
        }
        return new HttpResult(status, location, text);
    }

    private static HttpURLConnection open(URL url) throws IOException {
        HttpURLConnection c = (HttpURLConnection) url.openConnection();
        c.setConnectTimeout(5000);
        c.setReadTimeout(10000);
        c.setUseCaches(false);
        c.setRequestProperty("User-Agent", "LicenseRecover/1.2.13 localhost-native-registration");
        return c;
    }

    private static String readResponse(HttpURLConnection c) throws IOException {
        InputStream in = c.getResponseCode() >= 400 ? c.getErrorStream() : c.getInputStream();
        if (in == null) return "";
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] b = new byte[8192]; int n;
        while ((n = in.read(b)) >= 0) out.write(b, 0, n);
        in.close();
        String ct = c.getContentType();
        String charset = "UTF-8";
        if (ct != null) {
            Matcher m = Pattern.compile("(?i)charset=([^;\\s]+)").matcher(ct);
            if (m.find()) charset = m.group(1).replace("\"", "").trim();
        }
        try { return new String(out.toByteArray(), charset); }
        catch (Exception e) { return new String(out.toByteArray(), StandardCharsets.UTF_8); }
    }

    private static String collectCookies(URLConnection c) {
        List<String> values = c.getHeaderFields().get("Set-Cookie");
        if (values == null) values = c.getHeaderFields().get("set-cookie");
        if (values == null) return null;
        StringBuilder out = new StringBuilder();
        for (String raw : values) {
            if (raw == null) continue;
            String first = raw.split(";", 2)[0];
            if (out.length() > 0) out.append("; ");
            out.append(first);
        }
        return out.toString();
    }

    static List<URL> resolveLocalUrls(File appRoot, String pageName, Consumer<String> log) {
        LinkedHashSet<String> urls = new LinkedHashSet<String>();
        String appName = appRoot.getName();
        try { addIisUrls(urls, appRoot, pageName, log); } catch (Exception ex) {
            if (log != null) log.accept("[iis-native] IIS binding discovery unavailable: " + ex.getMessage() + "\n");
        }
        String encodedApp = pathSegment(appName);
        for (int port : new int[]{8088, 80, 8080}) {
            String hp = port == 80 ? "http://127.0.0.1" : "http://127.0.0.1:" + port;
            urls.add(hp + "/" + encodedApp + "/" + pageName + "?s=reg");
        }
        List<URL> out = new ArrayList<URL>();
        for (String s : urls) try { out.add(new URL(s)); } catch (Exception ignore) { }
        return out;
    }

    private static void addIisUrls(Set<String> urls, File appRoot, String pageName, Consumer<String> log) throws Exception {
        String windir = System.getenv("WINDIR");
        if (blank(windir)) windir = "C:\\Windows";
        File cfg = new File(windir, "System32\\inetsrv\\config\\applicationHost.config");
        if (!cfg.isFile()) return;
        DocumentBuilderFactory f = DocumentBuilderFactory.newInstance();
        f.setExpandEntityReferences(false); f.setXIncludeAware(false);
        try { f.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true); } catch (Exception ignore) { }
        Document doc = f.newDocumentBuilder().parse(cfg);
        NodeList sites = doc.getElementsByTagName("site");
        String wanted = canonical(appRoot);
        for (int i=0; i<sites.getLength(); i++) {
            Element site = (Element) sites.item(i);
            NodeList apps = site.getElementsByTagName("application");
            for (int j=0; j<apps.getLength(); j++) {
                Element app = (Element) apps.item(j);
                NodeList vdirs = app.getElementsByTagName("virtualDirectory");
                for (int k=0; k<vdirs.getLength(); k++) {
                    Element vd = (Element) vdirs.item(k);
                    String physical = expandEnv(vd.getAttribute("physicalPath"));
                    if (blank(physical) || !wanted.equalsIgnoreCase(canonical(new File(physical)))) continue;
                    String appPath = app.getAttribute("path");
                    if (blank(appPath)) appPath = "/";
                    NodeList bindings = site.getElementsByTagName("binding");
                    for (int x=0; x<bindings.getLength(); x++) {
                        Element b = (Element) bindings.item(x);
                        if (!"http".equalsIgnoreCase(b.getAttribute("protocol"))) continue;
                        String info = b.getAttribute("bindingInformation");
                        String[] parts = info.split(":", 3);
                        String port = parts.length > 1 && !blank(parts[1]) ? parts[1] : "80";
                        String host = parts.length > 2 ? parts[2] : "";
                        String authority = blank(host) ? "127.0.0.1" : host;
                        String base = "http://" + authority + ("80".equals(port) ? "" : ":" + port);
                        String path = "/".equals(appPath) ? "" : appPath;
                        urls.add(base + path + "/" + pageName + "?s=reg");
                    }
                }
            }
        }
    }

    private static File findRegistrationPage(File root) {
        File[] files = root.listFiles();
        if (files == null) return null;
        for (String wanted : new String[]{"Regester.aspx", "Register.aspx"})
            for (File f : files) if (f.isFile() && wanted.equalsIgnoreCase(f.getName())) return f;
        return null;
    }

    private static File findConfig(LicenseRecoverModernGUIAutoRecovery.Detection d) {
        File root = new File(d.appRoot, "config.xml"); if (root.isFile()) return root;
        File bin = new File(d.runtimeDir, "config.xml"); return bin.isFile() ? bin : null;
    }

    private static void blockSidecars(LicenseRecoverModernGUIAutoRecovery.Detection d,
                                      boolean backup, Consumer<String> log) throws Exception {
        List<File> files = new ArrayList<File>();
        add(files, new File(d.appRoot, "Web.config"));
        add(files, new File(d.appRoot, "web.config"));
        addSidecars(files, d.appRoot); addSidecars(files, d.runtimeDir);
        for (File file : files) {
            String original = new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
            String updated = AUTH_URL.matcher(original).replaceAll(BLOCK);
            if (original.equals(updated)) continue;
            if (backup) {
                File bak = uniqueBackup(file);
                Files.copy(file.toPath(), bak.toPath(), StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES);
                if (log != null) log.accept("[backup] " + bak.getAbsolutePath() + "\n");
            }
            Files.write(file.toPath(), updated.getBytes(StandardCharsets.UTF_8));
        }
    }

    private static void add(List<File> files, File f) { if (f != null && f.isFile() && !files.contains(f)) files.add(f); }
    private static void addSidecars(List<File> files, File dir) {
        if (dir == null || !dir.isDirectory()) return;
        File[] fs = dir.listFiles(); if (fs == null) return;
        for (File f : fs) {
            String n = f.getName().toLowerCase(Locale.ROOT);
            if (n.endsWith(".dll.config") || n.endsWith(".exe.config")) add(files, f);
        }
    }

    private static File uniqueBackup(File f) {
        String t = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        File b = new File(f.getParentFile(), f.getName() + "." + t + ".preiisnative.bak");
        int i=1; while (b.exists()) b = new File(f.getParentFile(), f.getName() + "." + t + "-" + (i++) + ".preiisnative.bak");
        return b;
    }

    private static Map<String,String> attributes(String tag) {
        LinkedHashMap<String,String> out = new LinkedHashMap<String,String>();
        Matcher m = ATTR.matcher(tag);
        while (m.find()) {
            String v = m.group(2) != null ? m.group(2) : (m.group(3) != null ? m.group(3) : m.group(4));
            out.put(m.group(1).toLowerCase(Locale.ROOT), v == null ? "" : v);
        }
        return out;
    }
    private static String encodeForm(Map<String,String> fields) throws Exception {
        StringBuilder out = new StringBuilder();
        for (Map.Entry<String,String> e : fields.entrySet()) {
            if (out.length() > 0) out.append('&');
            out.append(URLEncoder.encode(e.getKey(), "UTF-8")).append('=')
                    .append(URLEncoder.encode(e.getValue() == null ? "" : e.getValue(), "UTF-8"));
        }
        return out.toString();
    }
    private static String firstElement(String xml, String name) {
        Matcher m = Pattern.compile("(?is)<" + Pattern.quote(name) + "\\b[^>]*>\\s*([^<]*?)\\s*</" + Pattern.quote(name) + "\\s*>").matcher(xml == null ? "" : xml);
        return m.find() ? htmlDecode(m.group(1).trim()) : null;
    }
    private static String htmlDecode(String s) {
        if (s == null) return null;
        return s.replace("&quot;", "\"").replace("&#39;", "'").replace("&lt;", "<")
                .replace("&gt;", ">").replace("&amp;", "&");
    }
    private static boolean looksHex(String s) { return s != null && s.trim().matches("(?i)[0-9a-f]{32,}"); }
    private static String lower(String s) { return s == null ? "" : s.toLowerCase(Locale.ROOT); }
    private static boolean blank(String s) { return s == null || s.trim().isEmpty(); }
    private static String pathSegment(String s) { try { return URLEncoder.encode(s, "UTF-8").replace("+", "%20"); } catch (Exception e) { return s; } }
    private static String canonical(File f) { try { return f.getCanonicalPath(); } catch (Exception e) { return f.getAbsolutePath(); } }
    private static String expandEnv(String s) {
        if (s == null) return null;
        Matcher m = Pattern.compile("%([^%]+)%").matcher(s); StringBuffer b = new StringBuffer();
        while (m.find()) { String v = System.getenv(m.group(1)); if (v == null) v = m.group(); m.appendReplacement(b, Matcher.quoteReplacement(v)); }
        m.appendTail(b); return b.toString();
    }

    private static final class HttpResult {
        final int status; final String location, text;
        HttpResult(int s, String l, String t) { status=s; location=l; text=t; }
    }
}
